readme.md

Upstream Firedrake, FFC and UFL all now have a cofs branch that contains
the necessary combination of code to run COFS.

Readme: Point at cofs branches where master will not do

---

.travis.yml
cofs/utility.py
requirements.txt
test/conftest.py
test/continuity3d/test_continuity_mes.py
test/operations/test_operations_2d-3d.py
test/swe2d/test_steady_state_basin_mms.py

Sets up build testing on travis.  This branch is tested, for example, here: https://travis-ci.org/wence-/cofs/builds/96775578
Also pytestifies some of the tests using fixtures.
The travis testing framework uses travis caching to mean that we don't have to reinstall firedrake every time (also the FFC kernel cache is cached, so only the first run should require building the kernels).  These need to be manually invalidated if the dependencies are upgraded (but this is a one-click thing on the travis website).
I didn't activate code linting, because most of the source tree fails it!

Activate travis

---

cofs/options.py
cofs/shallowwater_eq.py
cofs/solver2d.py
test/swe2d/test_steady_state_basin_mms.py
test/swe2d/test_steady_state_channel_mms.py

Implements functionality for PnDG-P(n+1) family (SWE2D only at the moment). Changes are fairly minimal, only needed to add a case for "not integrating pressure gradient by parts".
Test added by running swe2d/test_steady_state_basin_mms.py with P1DG-P2 as well.
Again not really convinced of the options name (use_continuous_pressure). Any better ideas? Maybe we should have just one switch that offers mimetic/equal-order-dg/mixed-dg-cg ?

Pndg pnplus1

---

.travis.yml
cofs/limiter.py
cofs/momentum_eq.py
cofs/shallowwater_eq.py
cofs/timeintegrator.py
cofs/tracer_eq.py
cofs/turbulence.py
cofs/utility.py
examples/rhineROFI/rhineROFI.py
examples/rhineROFI/rhineROFI2d.py
install.md
readme.md
test/conftest.py
test/continuity3d/test_continuity_mes.py
test/swe2d/test_steady_state_channel_mms.py

The measure no longer contains mesh-specific information, and so we
don't have to a massive dance to save the correct meash object
everywhere.  Instead just use the global dx, ds, etc... as appropriate.
Move definitions of ds_bottom and ds_surf into utility.py.
Additionally, FunctionSpace objects no longer have a cdim, but rather a
shape and a dim property.  We need dim for the usages here.
Finally, now that the new form compiler has landed, we no longer have to
install a strange set of branches.

Updates for current Firedrake

---

examples/bottomFriction/steadyChannel.py
examples/channel3d/channel3d.py
examples/channel3d/channel3d_closed.py
examples/tracerBox/tracerBox3d.py
test/barotropicChannel/test_closed_channel.py
test/bottomFriction/test_implicit_friction_parabolic.py
test/bottomFriction/test_implicit_friction_turbulence.py
test/operations/test_operations_2d-3d.py
thetis/utility.py

3d mesh used to be extruded downwards from free surface to bottom which had some nasty side effects. For example, the top/bottom faces in firedrake corresponded to bottom/top faces in thetis. It also affected the sign of the jacobian of 3d elements etc.
This changes the extrusion direction to be from bottom to top, achievable with fairly minor changes to the code.

Extrude upwards

---

thetis/exporter.py
thetis/solver.py
thetis/solver2d.py

This is mostly relevant to 3D runs where memory consumption is a concern
- exporters use function spaces allocated in solver class
- ExportManager has dg coordinate function to avoid allocating one in File

decrease exporter memory footprint

---

examples/lockExchange/runTestSuite.py
examples/lockExchange/submitRuns.py
examples/overflow/overflow.py
examples/rhineROFI/rhineROFI.py
examples/rhineROFI/rhineROFI2d.py
examples/tracerBox/tracerBox3d.py
test/firedrake/test_divergence_2d.py
test/firedrake/test_implicit_diffusion.py
test/momentumEq/test_h-viscosity_mes.py
test/momentumEq/test_v-viscosity_mes.py
test/momentumEq/visu_viscosity.pvsm
test/slopelimiter/test_slopelimiter.py
test/tracerEq/test_h-diffusion_mes.py
test/tracerEq/test_v-diffusion_mes.py
test/tracerEq/visu_diffusion.pvsm
thetis/coupled_timeintegrator.py
thetis/exporter.py
thetis/limiter.py
thetis/momentum_eq.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/solver2d.py
thetis/timeintegrator.py
thetis/tracer_eq.py
thetis/turbulence.py
thetis/utility.py

Extending slope limiters to work correctly at boundaries

Slope limiter boundary treatment

---

thetis/coupled_timeintegrator.py
thetis/options.py
thetis/shallowwater_eq.py
thetis/solver2d.py
thetis/timeintegrator.py

Introduce semi-implicit time integration for SWE.
This is semi-implicit in the Casulli sense. By writing all terms in the
form A(u_nl)u we can easily switch between explicit (u_nl=u=u_old),
semi-implict (u_nl=u_old, u=u_new) and fully implicit (u_nl=u=u_new).
Currently only for CrankNicolson timeintegrator in combination with SWE.

Semi implicit new

---

examples/lockExchange/runTestSuite.py
examples/tracerBox/tracerBox3d.py
examples/waveEq2d/channel2d_waveEq.py
examples/waveEq3d/channel3d_waveEq.py
thetis/callback.py
thetis/exporter.py
thetis/solver.py
thetis/solver2d.py
thetis/utility.py

Rather than there always being a global communicator, we now build
meshes by passing in a communicator.  All subsequent operations are then
collective only over that communicator.  This defaults to COMM_WORLD.

Update for communicator changes in Firedrake

---

examples/lockExchange/lockExchange.py
test/momentumEq/test_h-viscosity_mes.py
test/tracerEq/test_h-diffusion_mes.py
test/tracerEq/test_v-diffusion_mes.py
thetis/coupled_timeintegrator.py
thetis/momentum_eq.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/tracer_eq.py
thetis/utility.py

Updated diffusion operators to handle DG0/RT spaces. DG0 uses the same IP term implementation, only a different penalty parameter value.
Sits on top of #62.

Viscosity for DG0/RT spaces

---

examples/lockExchange/lockExchange.py
examples/tidalfarm/tidalfarm.py
test/firedrake/test_implicit_friction.py
test/swe2d/test_steady_state_basin_mms.py
test_adjoint/test_swe_adjoint.py
thetis/limiter.py
thetis/timeintegrator.py
thetis/utility.py

Update to new way of specifying assembled matrix type in firedrake.  The requisite change in dolfin-adjoint will hopefully merge imminently.  That side of things also fixes remembering the assembled matrix type (so no need to specify it globally in the adjoint tests).

New firedrake matrix types

---

examples/stommel2d/stommel2d.py
examples/stommel2d/stommel2d_picard.py
test/swe2d/test_standing_wave.py
test/swe2d/test_steady_state_channel.py
test/swe2d/test_steady_state_channel_mms.py
thetis/options.py
thetis/solver2d.py
thetis/timeintegrator.py

New timestepper for 2D equations that combines a pressure projection approach with Picard iterations. Solves a preliminary (depth-averaged) separate momentum equation first (using the free surface elevation from the previous timestep or Picard iteration). Then solves the coupled system containing only the wave equations terms (mass terms and free surface gradient and continuity divergence term). These two solves can be iterated with a Picard iteration to increase the coupling between the free surface update and the full momentum equation, and in case this is combined with the use_linearized_semi_implicit_2d option (recommended) to reduce the error due to linearizing the advection and continuity divergence terms. With nonlinear terms that are merely quadratic, the second order accuracy of …

Pressure projection

---

test/bottomFriction/test_bottom_friction.py
test/continuity3d/test_continuity_mes.py
test/momentumEq/test_h-viscosity_mes.py
test/momentumEq/test_v-viscosity_mes.py
test/swe2d/test_steady_state_basin_mms.py
test/tracerEq/test_consistency.py
test/tracerEq/test_h-diffusion_mes.py

Travis has decided to timeout after 50 minutes instead of ~2 hours, so all builds are failing now.
I'm marking more tests as `not_travis` to skip them. In cases where there are multiple options to test, only 1 or 2 are being tested. I hope we can rely on drone for complete testing from now on.

Fix Travis timeout

---

test/slopelimiter/test_slopelimiter.py
thetis/limiter.py

This (partially) fixes lateral boundary issues discussed in #23  and #29.
To avoid limiting too much at the boundaries, we add the mean value of the field at the lateral boundary facets to the min/max fields. This works in cases where the solution is a linear function that does not attain min/max at a corner. In this case the limiter does not alter the linear function at all. If min/max occurs at the corner, then the corner element will still be limited.
This sits on top of #88.

Fix slope limiter at lateral boundary

---

test/swe2d/test_standing_wave.py
thetis/__init__.py
thetis/assembledschur.py
thetis/options.py
thetis/solver2d.py
thetis/timeintegrator.py

Add a AssembledSchurPC preconditioner that can be used to solve the schur system with the 'pressureprojectionpicard' timestepper. This gives very good performance with the dg-cg element pair for the depth-averaged equations.
The AssembledSchurPC provides a preconditioner for the schur system of the velocity-pressure system [[K,G],[C, P]] by explicitly assembling (an approximation to) it, assuming the velocity is DG and the velocity block K is just a mass matrix M. This is true for the pressureprojectionpicard time integration with dg-cg as the other terms in the momentum equation are solved in a separate step. dg-cg has the particular advantage that the stencil of C M^-1 G is compact (it's the same as that of the standard Laplacian in pressure space). For dg-dg it becomes a lot bigger. …

Assembledschur

---

thetis/equation.py
thetis/exporter.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/solver2d.py
thetis/timeintegrator.py
thetis/turbulence.py

We have to be careful that we iterate over dict-like objects in a
consistent order.  Arrange for that either by using OrderedDict or
iterating over sorted keys.

Fixes for non-deterministic iteration order

---

test/swe2d/test_standing_wave.py
thetis/__init__.py
thetis/callback.py
thetis/utility.py

Add a callback to write out interpolated fields at detector locations. Based on DiagnosticCallback, writes to diagnostic_detectors.h5 file.
Also includes a helper function that can select those detector locations
that are actually within the domain, and potentially move them inside
(if within some maximum distance) in the nearest cell centre.
Change default precision from dtype='f' (single precision) to dtype='d'
(double precision). All DiagnosticCallback derived callback classes can
pass a new hdf5_dtype keyword arg to override.

Detector callback

---

examples/tidalfarm/tidalfarm.py
test/swe2d/test_steady_state_channel.py
test/swe2d/test_steady_state_channel_mms.py
test_adjoint/test_swe_adjoint.py
thetis/utility.py

Not freeing this operation results in MPI crashing with error "cannot create too many user-defined reduction operations" when multiple restarts are done (in adaptive simulations for instance). Hence the proposed fix.

This PR frees a MPI user-defined operation, and OMG you won't believe what happens next

---

thetis/solver.py
thetis/solver2d.py

Restarts with a different dt can be useful: if the code crashed after a while due to too large dt and one wants to restart from a previous checkpoint, or in adaptive simulations where the size of the elements is not explicitly controlled. This is not currently supported by Thetis, however, it *seems*  the small change proposed in this PR fixes the issue.
It was tested in an adaptation context, with many restarts, and does not seem to break anything.
Tests pass, however there seems to be a difference in the output with master which I cannot explain:
the following is my branch:
```
=========================================================================== warnings summary ===========================================================================
None
Benchmarks are automatically disabled …
```

Fix restarts with a different dt

---

scripts/visualize-output.py
thetis/exporter.py

Storing all files in a single directory stalls the file system for large runs. For example, storing 10 output fields with 100 MPI processes and 500 time steps results in 500k files.
Now each field is stored in a separate sub-directory:
```
outputs/Salinity3d/Salinity3d.pvd
outputs/Salinity3d/Salinity3d_1.vtu
```

Store vtk fields to separate sub-directory

---

test/callback/test_diagnostic_hdf5_output.py
thetis/shallowwater_eq.py

Fixes issue #150, where setting elev=0 (a float) on a boundary will cause bathymetry being altered if wetting-drying is enabled.

Fix 2d solver for elev=0 boundary condition

---

Jenkinsfile
test/swe2d/test_standing_wave.py

This PR switches the Jenkins file to use docker. This has two impacts.
1. We don't have to build firedrake every time, we just inherit the latest master build.
2. We can run tests on 12 cores instead of 4.
The combination of these two cuts the test time in half. 1/3 of the remaining test time is taken by one adjoint test. It might be worth considering if this test can be shortened.

Dockerise the Jenkins file

---

Jenkinsfile
test/callback/test_diagnostic_hdf5_output.py

Fix the permissions in the build process.
Also run the forward and adjoint tests at the same time to cut down the wall time of the build.
Causes one test to fail. This test is doing something I really don't understand with output directories. I think we should merge this PR in order to fix tests for everyone, and then come back to work out what is going on with the test.

Forward adjoint tests parallel

---

test/callback/test_diagnostic_hdf5_output.py

Fixes hdf5 diagnostic test that was skipped in #159. All output is now written to tmp directory thus avoiding race conditions on parallel.

fix hdf5 diagnostic test

---

test/tracerEq/test_h-advection_mes_2d.py
thetis/coupled_timeintegrator_2d.py
thetis/options.py
thetis/tracer_eq_2d.py

Due to the coupled nature of Thetis, we cannot calculate the depth-averaged product **u**c required by the sediment concentration equation, but only the product of the depth-averaged **u** (from the hydrodynamic component) and the depth-averaged **c** (from the sediment transport component).
This addition allows us to add a correction factor to the tracer advection equation to account for this error. More details about this correction factor can be found in:
_Huybrechts, N., Villaret, C., & Hervouet, J. M. (2010, September). Comparison between 2D and 3D modelling of sediment transport: application to the dune evolution. In River Flow (pp. 887-893)._

Tracer advection equation

---

test/swe2d/test_thacker.py
thetis/options.py
thetis/rungekutta.py
thetis/solver2d.py

Implements `rungekutta.DIRKGenericUForm` which solves the implicit equations for each sub-solution `u^(i)` instead of the tendencies. This is compatible with the wetting-drying method. Replaces previous DIRK solvers in the 2D model. Adresses #172 .
This adds a new option to all implicit 2D schemes: `options.use_semi_implicit_linearization`. The default value is `True`, consistent with the `CrankNicolson` time stepper. Previously, the DIRK schemes did not have this feature.

Fix DIRK time-steppers for wetting-drying

---

test/momentumEq/test_v-viscosity_mes.py
test/tracerEq/test_v-diffusion_mes.py
thetis/rungekutta.py

Fixes gamma parameter in DIRK22 time stepper.
2nd order 2-stage DIRK, `rungekutta.DIRK22`, should have `gamma = (2 - \sqrt{2})/2`. Current implementation has `(2 + \sqrt{2})/2`. Both values result in a 2nd order scheme, but the minus one is the preferred one.

Fix DIRK22 gamma parameter

---

thetis/coupled_timeintegrator.py
thetis/field_defs.py

As we update baroclinic/turbulence terms only at the end of the time
step, using a 2nd order two-stage (DIRK22) scheme does not bring any benefit
in turbulence problems, but does increase the cost by 2x.

3D solver: use backward Euler in implicit vertical problem

---

examples/lockExchange/lockExchange.py
test_adjoint/examples/test_examples.py
test_adjoint/test_swe_adjoint.py

Adjoint is currently broken, see issue #184. We are thus temporarily skipping the adjoint tests.

Temporarily disable adjoint test

---

thetis/options.py
thetis/shallowwater_eq.py

An extra option was also added to the solver object to smooth the velocity norm in the friction term in the shallow water equations. This is to avoid non-differentiable functions in the continuous formulation and is discussed in section 2.1 in "Funke, S., Farrell, P., & Piggott, M. (2017). Reconstructing wave profiles from inundation data. Computer Methods in Applied Mechanics and Engineering, 322, 167–186. Retrieved from https://arxiv.org/pdf/1612.09597.pdf". The default is that this smoother = 0 unless set by the user and thus all tests should be unaffected by this change.

Dirk22 and norm smoother

---

thetis/options.py

As it stands, the wetting and drying parameter which ensures a positive water height is assumed to be constant across the domain. Whilst this is a reasonable assumption for many problems, in some cases it would be advantageous to allow the parameter to vary spatially. One example is the case where we seek to model inundation of a coast near to a deep ocean trench with sharp gradients.
In a future PR we could consider automatically selecting the (spatially varying) wetting and drying parameter in a similar way as was done for the SIPG parameter in PR #176.

Allow wetting and drying alpha to vary spatially

---

test/operations/test_operations_2d-3d.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/solver2d.py
thetis/utility.py

This PR extends the automatic SIPG parameter generation implemented in #176 so that it is allowed to vary in space.
SIPG parameters for all equations (momentum/swe/tracer) default to `Constant`s, but can be set as P0 fields. Where the previous PR computed the minimum angle in all elements and multiplied it by the maximum ratio of viscosity or diffusivity (as appropriate) in all elements, this PR actually takes the elementwise values, in line with [Epshteyn & Riviere, 2007].

Spatially varying SIPG parameter

---

examples/tidalfarm/tidalfarm.py
test_adjoint/examples/test_examples.py
test_adjoint/test_swe_adjoint.py

Two of the adjoint tests were xfailed as a temporary measure due to changes in Firedrake. Following recent fixes in Firedrake, the tests now pass and can be included in the test suite again.

Un-xfail adjoint tests

---

test/swe2d/test_rossby_wave.py

Running `test_rossby_wave.py` for just SSPRK33 and dg-dg uses
* ~1.75GB at the original reference_refinement_level=768
* ~273MB at the reduced reference_refinement_level=96
The test also runs a lot quicker at the lower refinement level.
Given that this test has recently caused Jenkins to crash, reducing unnecessarily high resolution would probably be a good idea.

Reduce reference mesh refinement level for Rossby wave test

---

examples/balzano/balzano.py
test/tracerEq/test_consistency_2d.py
test/tracerEq/test_steady_adv-diff_mms_2d.py
thetis/callback.py
thetis/conservative_tracer_eq_2d.py
thetis/options.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/solver2d.py
thetis/tracer_eq_2d.py
thetis/utility.py

Conservative tracer equation, guarantees conservation of tracer also with wetting and drying and discontinuous bathymetry. New implementation as discussed, now solves for depth-integrated `q=Hc` tracer. Includes tests. Separated depth functions (based on wetting and drying options and nonlinear switch) in separate class to make these available in both `ShallowWaterTerm`s and `TracerTerm`s but also in diagnostics.

Conservative tracer equation in 2D

---

examples/tidalfarm/tidalfarm.py
setup.py
test_adjoint/conftest.py
test_adjoint/test_swe_adjoint.py
thetis/callback.py
thetis/configuration.py
thetis/exporter.py
thetis/firedrake.py
thetis/limiter.py
thetis/optimisation.py
thetis/options.py
thetis/physical_constants.py
thetis/solver.py
thetis/timeintegrator.py
thetis/turbines.py
thetis/utility.py
thetis_adjoint/__init__.py
thetis_config/__init__.py

This simplifies the code a lot as we no longer need a thetis_adjoint
thetis_config and a thetis/firedrake and no longer need to distinguish
between FiredrakeFunction (which was always the "real"
firedrake.Function and Function which was potentially the wrapped
firedrake_adjoint.Function).
Also removes a number of other workarounds (e.g. stop_annotation() around
split())

Use new integrated firedrake adjoint

---

test/tracerEq/test_bcs_2d.py
test/tracerEq/test_consistency_2d.py
test/tracerEq/test_h-advection_mes_2d.py
test/tracerEq/test_h-diffusion_mes_2d.py
test/tracerEq/test_steady_adv-diff_mms_2d.py
thetis/coupled_timeintegrator_2d.py
thetis/options.py
thetis/solver2d.py

Currently the 2D tracer equation only supports `'CrankNicolson'` timestepping. This PR is a rewrite of PR #197 which attempted to extend to five other schemes, but involved quite a bit of code duplication.
The updated version reduces duplication and provides a `CoupledMatchingTimeIntegrator2D` class which implies matching integrators for both shallow water and tracer solvers. The following additional schemes are considered: ForwardEuler, BackwardEuler, DIRK22, DIRK33, SSPRK33.
Statuses of 2D tracer tests following these changes:
* `test_h-advection_mes_2d.py`: all pass except BackwardEuler
* `test_h-diffusion_2d.py`: all pass
* `test_bcs_2d.py`: all pass
* `test_consistency_2d.py`: all pass if overshoot tol loosened from `1e-12` to `1e-11` and conservation tol loosened from `1e-4` to …

Timesteppers other than Crank-Nicolson for 2D tracer

---

examples/baroclinic_channel/baroclinic_channel.py
examples/baroclinic_eddies/baroclinic_eddies.py
examples/bottomFriction/steadyChannel.py
examples/channel3d/channel3d.py
examples/channel3d/channel3d_closed.py
examples/columbia_plume/cre-plume.py
examples/dome/dome.py
examples/katophillips/katophillips.py
examples/tracerBox/tracerBox3d.py
examples/waveEq3d/channel3d_waveEq.py
test/pressure_grad/test_int_pg_mes.py
test/pressure_grad/test_pg-stack_mes.py
thetis/coupled_timeintegrator.py
thetis/field_defs.py
thetis/momentum_eq.py
thetis/solver.py
thetis/tracer_eq.py
thetis/tracer_eq_2d.py
thetis/utility.py

Adds `ExtrudedFunction` class which allows using 2D fields in extruded 3D mesh:
```python
mesh2d = ...
mesh3d = ExtrudedMesh(mesh2d, ...)
fs_2d = FunctionSpace(mesh2d, ...)
f_2d = ExtrudedFunction(fs_2d, mesh_3d=mesh3d)  # this behaves like a 2D Function
f_3d = f_2d.view_3d  # this can be used in 3D equations, shares the data with f_2d
```
The 3D function lives in Foo x R extruded function space.
Under the hood there's `extend_function_to_3d` function:
```python
f_3d = extend_function_to_3d(f_2d, mesh_3d)
```
In this PR, `ExtrudedFunction` is used for elevation and bathymetry fields, reducing the total memory footprint of the 3D solver.
The following auxiliary fields are removed:
- `bathymetry_3d`
- `elev_3d`
- `uv_p1_3d`
- `uv_mag_3d`
- `w_mesh_surf_2d`
- `w_mesh_surf_3d`
- `elev_cg_3d` …

Use 2D Functions in 3D equations

---

thetis/assembledschur.py
thetis/timeintegrator.py

Firedrake `assemble` no longer supports `inverse=True` option. This PR fixes inverse mass matrix assembly calls.

Fix inverse assembly

---

examples/lockExchange/plotting.py
test/firedrake/test_implicit_friction.py
thetis/utility.py

variant='equispaced' is no longer allowed with Hdiv elements (previously ignored). Should be variant='point' (old default, which under-integrates) or variant='integral' (soon to be new default). For the moment I've fixed the variant to 'point' for RT.
FWIW, I've locally run all tests that mention 'rt-dg' with variant='integral', and I get 3 failures:
2 failures in test/bottomFriction/test_ekman_bottom.py that look like they might just be a tolerance tweak
1 failure in test/swe2d/test_atmospheric_pressure.py where I get a DIVERGED_LINEAR_SOLVE

Fix rt variant

---

thetis/configuration.py
thetis/options.py
thetis/utility.py

Change ObserveHandler and DefaultHandler to decorators observe and
default, which seem to do the same.
For some reason we can't overwrite the default_value attribute of
PETScSolverParameters.
Fixes #223

Fix compatibility with traitlets 5

---

test/swe2d/test_thacker.py
thetis/options.py
thetis/solver2d.py
thetis/utility.py

This PR allows the wetting and drying alpha parameter to be set automatically as a P1 field.
It follows the recommendation in [Karna et al. 2011]:
\alpha \approx |L_x \nabla h|,
where L_x is the horizontal length scale of mesh elements at the wet-dry interface and h is the bathymetry.
An approximation is used here:
element_width_x * abs(h_x) + element_width_y * abs(h_y).
The value may be capped using `options.wetting_and_drying_alpha_max`, which is set to 2 by default.

Automatic wetting and drying alpha

---

Makefile
test/bottomFriction/test_bottom_friction.py
test/bottomFriction/test_ekman_bottom.py
test/bottomFriction/test_ekman_surface.py
test/momentumEq/test_h-viscosity_mes.py
test/momentumEq/test_v-viscosity_mes.py
test/pressure_grad/test_int_pg_mes.py
test/pressure_grad/test_int_pg_zero.py
test/pressure_grad/test_pg-stack_mes.py
test/swe2d/test_anisotropic.py
test/swe2d/test_atmospheric_pressure.py
test/swe2d/test_rossby_wave.py
test/swe2d/test_steady_state_basin_mms.py
test/swe2d/test_steady_state_channel_mms.py
test/tracerEq/test_consistency.py
test/turbulence/test_katophillips.py
test_adjoint/conftest.py
test_adjoint/test_swe_adjoint.py
thetis/implicitexplicit.py
thetis/momentum_eq.py
thetis/options.py
thetis/rungekutta.py
thetis/solver.py
thetis/solver2d.py
thetis/timeintegrator.py
thetis/utility.py

Adds support for BDM-DG discretization in both 2D and 3D models. Setting `options.element_family` to `bdm-dg` gives the BDM(n+1)-P(n)DG velocity-pressure pair. Supports both triangles and quads. Also the `rt-dg` option now works for quads as well.
In the 3D solver, bottom friction treatment has been revised. Vertical diffusion of momentum is now computed for the full velocity (depth average + deviation) instead of the deviation component only. In addition, the computation of the drag coefficient from the bottom roughness length has been revised: the friction term is now defined for the velocity at the bottom (z=-h), and we use a parametrized value for the drag. These updates ensure positivity of the velocity, i.e. there can be no spurious sign changes in the bottom element due to friction …

BDM function space

---

test/sphere/test_williamson.py
thetis/shallowwater_eq.py
thetis/solver2d.py
thetis/utility.py

Generalizes the 2D shallow water model to spherical meshes. Adds convergence tests for Williamson 2 and Läuter 3 test cases. Williamson 5 test is included without a correctness check.
To run the 2D model on the sphere, create a mesh on spherical surface, and call `init_cell_orientations`:
```python
mesh2d = IcosahedralSphereMesh(radius=r_earth, refinement_level=refinement, degree=3)
mesh2d.init_cell_orientations(SpatialCoordinate(mesh2d))
```
Note that in spherical geometry the curvature of the elements affects the model accuracy; For coarse grids, it's recommended to use coordinates with degree 2 or larger.
Spherical geometry only works with HDiv velocity spaces, i.e. the `'rt-dg'` and `'bdm-dg'` element families.

Shallow water on the sphere

---

test/momentumEq/test_h-viscosity_mes.py
test/momentumEq/test_v-viscosity_mes.py
test/swe2d/test_anisotropic.py
test/swe2d/test_steady_state_channel_mms.py
test/tracerEq/test_h-diffusion_mes.py
test/tracerEq/test_h-diffusion_mes_2d.py
test/tracerEq/test_steady_adv-diff_mms.py
test/tracerEq/test_steady_adv-diff_mms_2d.py
test/tracerEq/test_v-diffusion_mes.py
thetis/conservative_tracer_eq_2d.py
thetis/momentum_eq.py
thetis/options.py
thetis/sediment_eq_2d.py
thetis/shallowwater_eq.py
thetis/solver.py
thetis/solver2d.py
thetis/tracer_eq.py
thetis/tracer_eq_2d.py
thetis/turbulence.py

Implement a simpler form for symmetric interior penalty coefficient following Koen Hillewaert's [PhD thesis](https://dial.uclouvain.be/pr/boreal/object/boreal:128254/datastream/PDF_01/view).
In this method the "element size" length scale is defined as `CellVolume(mesh)/FacetArea(mesh)` making it robust for skewed elements as well. Compared to the theoretical bound, the IP penalty term has been multiplied by 2 as it seems to stable in practice.
This PR:
- Removes the now unnecessary `use_automatic_sipg_parameter` option
- Replaces the `sipg_penalty` options by `sipg_factor` which just scales the IP penalty term (defaults to 1.0)

Revised interior penalty coefficient

---

docs/source/model_formulation_2d.rst
test/swe2d/test_anisotropic.py
test/swe2d/test_rossby_wave.py

Couple of things:
* `test_rossby_wave` wasn't always properly assessing convergence, because the error metrics can approach 1 from above or below.
* `test_anisotropic` had turbines which didn't align with the underlying adapted mesh.
The BDM-DG pair is also added to the finite element pair list on the 2D solver doc page.

Fixes in two swe2d tests

---

docs/source/model_formulation_2d.rst
docs/source/tracer_formulation_2d.rst
test/operations/test_operations_2d-3d.py
test/tracerEq/test_bcs_2d.py
test/tracerEq/test_point_discharge.py
thetis/conservative_tracer_eq_2d.py
thetis/equation.py
thetis/options.py
thetis/sediment_eq_2d.py
thetis/solver2d.py
thetis/tracer_eq_2d.py
thetis/utility.py

I've been using P1+SUPG for various things in my PhD work, with the SUPG parameter advocated in [Micheletti et al. 2003], which accounts for element anisotropy. I thought maybe this would be useful for other people using Thetis?
This PR allows for CG tracers in 2D. The default is still DG. If SUPG is used then the test function of the tracer equation is modified, including the modified cell size.
In doing this, I thought it made sense to pass `options` to the tracer solver (in the same way as is done for the SW solver), instead of passing individual parameters. Is that okay? Also, I needed to make the tracer equation aware of the SW velocity field.
I didn't want to add too much to the test suite, so am just testing steady state and for BC implementation. Note that the CG tracer equation …

P1+SUPG for 2D tracer model

---

test/operations/test_operations_2d-3d.py
thetis/forcing.py
thetis/limiter.py
thetis/utility.py

Firedrake boundary method `'geometric'` has been removed in firedrakeproject/firedrake#2007
~For most (all?) Thetis use cases there's actually no difference between _geometric_ and _topological_ boundary masks (e.g. P1DG).~
The top/bottom facet mask indices have now been implemented manually.

remove geometric boundary mask

---

examples/lockExchange/lockExchange.py
examples/lockExchange/plotting.py
thetis/callback.py

Adds a callback for storing structured grid transects of 3D fields. Transect is defined by user-specified (x,y) coordinates and number of points in the vertical direction. The vertical coordinate of the transect adapts to the moving grid. The callback is included in the lock exchange example so that it'll be executed in the test suite.

Transect callback

---

thetis/implicitexplicit.py
thetis/rungekutta.py
thetis/timeintegrator.py

Since #247 TimeStepperOptions are passed directly to the
timeintegrators. For this an options argument was added to __init__ of
TimeIntegrator and all its subclasses, however the subclasses didn't
actually pass on the new argument when calling super().__init__ I think
the reason this didn't break anything was because the _optional_
solver_parameters was substituted for the required options argument -
because the solver_parameters weren't passed through a keyword in the
call. This means that _all_ solver_parameters will have been assumed
not-provided which probably only worked because it then uses Firedrake's
default of using mumps.
Better to always use the keyword in the call to a function for keyword
arguments - as the convention is that the order of these may change.
Also it masks any …

Fix passing of timestepper options.

---

docs/source/_themes/thetis/layout.html
docs/source/_themes/thetis/static/thetis.css_t
docs/source/conf.py
docs/source/index.rst

- fix link to GitHub Actions build status badge
- remove Jenkins link from the menu
- tweak layout of the build status side bar
- bump copyright year to 2021

Fix build badge image on homepage

---

thetis/utility.py

We've long deprecated `Expression` objects, https://github.com/firedrakeproject/firedrake/pull/2202 finally removes them. Cull the only reference in thetis to them.

Remove reference to firedrake.Expression

---

test/operations/test_diagnostics.py
test/swe2d/test_anisotropic.py
test/swe2d/test_rossby_wave.py
test/swe2d/test_standing_wave.py
thetis/__init__.py
thetis/diagnostics.py
thetis/exporter.py
thetis/utility.py

Building upon PR #242, maybe this will be useful for other people (e.g. in #277).
To use it in practice, do something like
```
from thetis.recovery import HessianRecoverer2D
P1_ten = TensorFunctionSpace(mesh2d, 'CG', 1)
hessian_2d = Function(P1_ten)
hessian_calculator = HessianRecoverer2D(hessian_2d, solver_obj, 'elev_2d')
solver_obj.add_new_field(hessian_2d, 'hessian_2d', 'Hessian of elevation', 'Hessian2d', preproc_func=hessian_calculator.solve)
solver_obj.options.fields_to_export = ['hessian_2d']
```

HessianRecoverer2D

---

thetis/rungekutta.py
thetis/shallowwater_eq.py
thetis/solver2d.py

User can now define a quadratic drag term on any boundary by adding a `'drag'` key to the boundary condition dictionary:
```python
land_bnd_id = 1
land_bnd_funcs = {
'drag': Constant(0.01),  # quadratic drag coefficient
}
solver_obj.bnd_functions['shallow_water'] = {
land_bnd_id: land_bnd_funcs,
}
```
Other updates:
- Adds correct linearization in `DIRKGeneric` time integrator
- The Coriolis, advection and friction terms are treated implicitly
- All function spaces are created with `get_functionspace` routine

Add boundary drag term to shallow water equations

---

thetis/__init__.py
thetis/log.py
thetis/solver.py
thetis/solver2d.py

Trying to address #290, I have updated the `log.py` implementation and added a `set_log_directory` method by which the user can define the log directory early on:
```python
from thetis import *
set_log_directory('my_directory')  # this actually creates the dir and empty log file
print_output('now this goes to the log file')
```
`solver.create_timestepper` now calls `set_log_directory` internally. If the user calls `set_log_directory` twice with the same target, the second call has no effect (e.g. does not remove old log). If called again with a different target directory, a warning is raised:
```python
from thetis import *
set_log_directory('dir1')
set_log_directory('dir2')  # raises warning, will not delete previous dir nor log file
solver_obj = solver2d.FlowSolver2d(...) …
```

Logger: add set_log_directory

---

examples/channel_inversion/inverse_problem.py
examples/tohoku_inversion/inverse_problem.py
thetis/inversion_tools.py

This PR adds two helper functions for inversion problems:
* default kwargs to pass to `ReducedFunctional`, namely a gradient evaluation callback;
* extract the cost function from the various inversion objects.
Inside `get_cost_function`, it also supports weighting the contributions at each station by the associated variance in the data. I turned this on for the Tohoku example and it appears to DTRT in my local runs.

Weighted cost function

---

examples/tohoku_inversion/Makefile
examples/tohoku_inversion/forward_run.py
examples/tohoku_inversion/inverse_problem.py
examples/tohoku_inversion/model_config.py
examples/tohoku_inversion/plot_convergence.py
examples/tohoku_inversion/plot_elevation_initial_guess.py
examples/tohoku_inversion/plot_elevation_optimised.py
examples/tohoku_inversion/plot_elevation_progress.py
examples/tohoku_inversion/plot_optimised_source.py
test/examples/test_examples.py
thetis/inversion_tools.py
thetis/utility.py

This PR adds two additional source models to the Tohoku inversion example. Instead of inverting for a field in CG or DG space, we invert for an array of controls in R-space, which provide the coefficients for linear combinations of basis functions.
Note that this PR includes commits from #300, so that will need to be merged first.

Tohoku: add 'radial' and 'box' source models

---

thetis/utility.py

The utility function `get_facet_areas` is broken because we are no longer allowed to assemble the diagonal on interior facets. Switching from Jacobi to SOR is probably sufficient.

Fix `get_facet_areas`

---

examples/channel_inversion/inverse_problem.py
examples/tohoku_inversion/inverse_problem.py
thetis/inversion_tools.py

I had a think about the way we are doing inversion and thought perhaps the API could be a bit simpler.
My idea here is to drop `OptimisationProgress` and create an `InversionManager` class that does almost everything that you would want for inversion problems. I decided to have `RegularizationManager` be created inside of it because `InversionManager` handles the controls and you need these to setup the regularisation. So the only thing that you still have to create separately is the `StationObservationManager`.
Hopefully it is agreeable. The only thing I am wondering is if the code style could be more like Thetis' solver objects by introducing a frozen `InversionOptions` class (like `ModelOptions`) that comes with `InversionManager` and which you modify afterwards, as opposed to passing …

InversionManager

---

thetis/configuration.py

Fix `textwrap.indent` call in docs generation.

docs: fix indent from textwrap

---

test/swe2d/test_anisotropic.py
test/tracerEq/test_point_discharge.py
thetis/diagnostics.py
thetis/utility.py

This PR adds `ShallowWaterDualWeightedResidual2D` and `TracerDualWeightedResidual2D` for doing goal-oriented error estimation in 2D. It tests them in `test/tracerEq/test_point_discharge.py` and `test/swe2d/test_anisotropic.py`, but also trims those tests so that the test suite doesn't get too much bigger overall.
On the coarse uniform meshes, the tracer estimator looks like
and the SW one looks like
These are consistent with work I've done on those test cases.

Dual weighted residual error indicators

---

thetis/configuration.py

Since traitlets 5.7.0 a lot more additional stuff happens in the initialisation of a HasTraits class (that is the initialisation of the class itself through its metaclass __init__()). All traits are assumed to be present already as class attributes and are registered internally in this initialisation. This means if we dynamically add traits to the class in a class decorator, we need reinitialize the class.

Fix traitlets

---

examples/channel_inversion/inverse_problem.py
examples/discrete_turbines/channel-optimisation.py
thetis/inversion_tools.py
thetis/optimisation.py
thetis/timeintegrator.py

Changes required to fix adjoint:
* Constants used as control (and any Constant that changes value during the run) requires a domain for the adjoint to work
* callbacks pre and post derivative calculation of a ReducedFunctional now need to pass through resp. the control and the derivatives
* avoid assigning to Constants internally as this causes issues with the adjoint - notably this was done in updating fields_old in some timesteppers (we maybe should just get rid of fields_old altogether)

Fixing issues around domain-less Constants and adjoint

---

test/swe2d/test_rossby_wave.py

The call to options.update(model_options) which a.o. sets the element_family option only happened after the call to create_function_spaces() so that the function spaces were always based on the default dg-dg rather than going through dg-dg, dg-cg, rt-dg and bdm-dg as intended.
Also the setting of the timestepper type should probably not be repeated as it may overwrite the timestepper sub-options that were set previously.

BUGFIX: Rossby wave test was being run on dg-dg only

---

examples/discrete_turbines/channel-optimisation.py
examples/discrete_turbines/tidal_array.py
examples/tidalfarm/tidalfarm.py
thetis/options.py
thetis/solver2d.py
thetis/turbines.py

- Farms must now be defined in a list for each subdomain ID
- Warning provided when a list is not used
- Corresponding updates to examples

Allow multiple tidal energy farms per subdomain

---

examples/columbia_plume/bath_smoothing_test.py
test/examples/test_examples.py
test/sediment/test_sed_slide.py

* test_sed_slide.py: this was previously a run-alone python script, but since pytest tries to import every python file starting with test_ it means this test was always being run even when trying to run a single actual pytest test. Now turned into an actual test
* test_examples: this test runs all python files (except those excluded) found in the examples/ directories. However the id was set to just the basename of these python files, and since there are multiple files with the same name in different subdirectories of examples/, you end up with multiple tests with the exact same name, meaning you can't easily work out which one has actually failed from the actions logs and also you can't run them individiually. Now just using the full path as the id. Note that the -k argument for pytest …

Various fixes to improve running of pytest suite

---

examples/channel_inversion/Makefile
examples/channel_inversion/inverse_problem.py
examples/channel_inversion/plot_elevation_progress.py
thetis/inversion_tools.py

- Correct file paths in example for plotting
- Correct VTKFile paths for import
- Load times for the optimisation fields (one timestep less than existing files)
- Import from collections.abc (deprecation update)
- Update makefile so it works again and cycles through all the stations for plotting

Update channel inversion example

---

demos/demo_2d_multiple_tracers.py
demos/demo_2d_tracer.py
examples/baroclinic_eddies/diagnostics.py
examples/channel_inversion/inverse_problem.py
examples/discrete_turbines/channel-optimisation.py
examples/lockExchange/diagnostics.py
examples/tohoku_inversion/sources.py
test/firedrake/test_domain_constant.py
test/operations/test_diagnostics.py
test/swe2d/test_rossby_wave.py
test/swe2d/test_steady_state_channel.py
test/tracerEq/test_bcs_2d.py
thetis/inversion_tools.py
thetis/utility.py

1) Don't use Constant(value, domain=mesh). New utility function
domain_constant(value, mesh) that creates Function in R space
2) Don't use interpolate(expr, V) (without assemble) instead use
Function(V).interpolate(expr)

Reduce Firedrake deprectation warnings

---

test/swe2d/test_anisotropic.py

Closes #379.
Thanks to @cpjordan for explaining how to update this example to use the more up-to-date turbine implementation. (Equations need to be created after turbine farm.)
I also added a check to avoid this happening again.

Re-enable turbines in `test_anisotropic`

---

thetis/coupled_timeintegrator_2d.py

The advance method of a timeintegrator should always advance from the solved-for-fields, which are the same fields that will contain the solution at the end of the timestep _after_ calling advance(). This is because this is the only field(s) that the "user" of a time integrator has control over, and the user may want to adjust/overwrite/project (for adaptivity) at the end of a timestep and expect the timestepper to advance from the adjusted values in the next timestep.
Thus, if a time-integrator stores some copy of a "solution_old" it should be set at the _beginning_ of advance() to the current solution, rather than at the end.

Fix NonHydrostaticTimeIntegrator2D for projection of solutions with adaptivity

---

thetis/timeintegrator.py

This is now strictly checked in Firedrake

assemble(1form, tensor=..) requires cofunction

---

examples/channel_inversion/inverse_problem.py
examples/tohoku_inversion/inverse_problem.py
test_adjoint/examples/test_examples.py

Updates scaling in the channel and Tohoku inversion examples and add the channel inversion back into testing.
- Previously the scaling has no effect because [`construct_evaluator`](https://github.com/thetisproject/thetis/blob/master/thetis/inversion_tools.py#L468) of the `StationManager` in `inversion_tools.py` has already been called and thus `cost_function_scaling_0d` does not get updated, even if `cost_function_scaling` does.
- The scaling itself needs to be higher than previously and seems to be related to the magnitude of dJ/dm rather than J
Cannot be merged until Firedrake PR [#3932](https://github.com/firedrakeproject/firedrake/pull/3932) is merged.

Update scaling for adjoint problems

---

thetis/options.py
thetis/turbines.py

- Concentrates the thrust into a smaller (or larger) area, allowing a narrower or wider wake for the same applied thrust
- Swept diameter defaults to normal diameter
- No changes to the examples
Based on [previous feature of OpenTidalFarm](https://github.com/OpenTidalFarm/OpenTidalFarm/blob/master/opentidalfarm/turbines/thrust_turbine.py).

Add projected area option for turbines

---

.github/workflows/build.yml
pyproject.toml
setup.py
test/examples/test_notebooks.py

Hi, I have had a go at getting `pip install Firedrake` (https://github.com/firedrakeproject/firedrake/pull/4011) support added to your CI (and also made you a `pyproject.toml`).
The website will also need updating.
Note that I haven't yet figured out how to get versioneer working properly. If you feel strongly about keeping it then some extra hacking around is needed. I have simply removed references to it in the build process and set the version to 0.0.1 for now.

pip install firedrake support

---

thetis/forcing.py
thetis/interpolation.py

Related to issue #397.
Adding the kwargs: `time_variable_name` to `ATMInterpolator` (and `ATMNetCDFTime`) in `thetis/thetis/forcing.py`.
This should allow user to input their own time variable name, pass it to all the inherited and required classes.

User-defined time_variable_name in ATMInterpolator

---

thetis/callback.py

Detector locations seem to be missing from the DetectorsCallback but present in e.g. TimeSeriesCallback2D. I've added them as variable attributes to avoid any ambiguity in the case where the keys of the hdf5 file default to 'detectors0N'.

Add detector locations in DetectorsCallback
