- cofs/coupledTimeIntegrator.py
- cofs/limiter.py
- cofs/solver.py
- cofs/turbulence.py
- cofs/utility.py
- test/bottomFriction/test_implicit_friction_parabolic.py
- test/bottomFriction/test_implicit_friction_turbulence.py
- test/bottomFriction/visu_implicit_friction_turbulence.pvsm
- test/conftest.py
- test/continuity3d/test_continuity_mes.py
- test/operations/test_operations_2d-3d.py
- test/swe2d/test_steady_state_basin_mms.py
- test/tracerEq/test_steady_adv-diff_mms.py
- tox.ini
Remove hazardous `linProblemCache` from utility.py following issue #5 . All functions that used to cache solvers are now implemented as classes who hold their solvers as members.
> Exterminate problem cache

- cofs/options.py
- cofs/solver.py
- cofs/solver2d.py
- examples/bottomFriction/steadyChannel.py
- examples/channel2d/channel2d.py
- examples/channel3d/channel3d.py
- examples/channel3d/channel3d_closed.py
- examples/freshwaterCylinder/freshwaterCylinder.py
- examples/geostrophicGyre/geoGyre2d.py
- examples/lockExchange/lockExchange.py
- examples/lockExchange/runTestSuite.py
- examples/overflow/overflow.py
- examples/rhineROFI/rhineROFI.py
- examples/rhineROFI/rhineROFI2d.py
- examples/stommel2d/stommel2d.py
- examples/stommel3d/stommel3d.py
- examples/tracerBox/tracerBox3d.py
- examples/waveEq2d/channel2d_waveEq.py
- examples/waveEq3d/channel3d_waveEq.py
- test/barotropicChannel/test_closed_channel.py
- test/bottomFriction/test_implicit_friction_parabolic.py
- test/bottomFriction/test_implicit_friction_turbulence.py
- test/continuity3d/test_continuity_mes.py
- test/swe2d/test_steady_state_basin_mms.py
- test/swe2d/test_steady_state_channel.py
- test/swe2d/test_steady_state_channel_mms.py
- test/tracerEq/test_steady_adv-diff_mms.py
Test cases should not create any files.
> No export option

- cofs/exporter.py
- cofs/limiter.py
- cofs/solver.py
- cofs/utility.py
- test/firedrake/test_implicit_friction.py
This renaming has now happened in firedrake, so do the same here.
> Rename OuterProductElement -> TensorProductElement

- cofs/callback.py
- cofs/solver.py
- cofs/solver2d.py
- cofs/timeintegrator.py
- cofs/utility.py
- test/tracerEq/test_consistency.py
Fixes tracer consistency (preservation of constant tracers) for DG elements.
Also
- adds tracer consistency test
- runtime validation checks are callback objects whose latest value is accessible in python
- e.g mass conservation, volume conservation, tracer overshoots checks
- more robust method to extrude sigma meshes with PyOP2 kernel
> Tracer consistency

- thetis/exporter.py
- thetis/limiter.py
- thetis/momentum_eq.py
- thetis/shallowwater_eq.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/utility.py
Change required when firedrakeproject/firedrake#713 is merged.
> MixedFunctionSpace type no longer user exposed

- test/conftest.py
- test/continuity3d/test_continuity_mes.py
- test/swe2d/test_steady_state_basin_mms.py
- test/tracerEq/test_steady_adv-diff_mms.py
- thetis/exporter.py
- thetis/solver.py
- thetis/utility.py
Addressing #5 remove hacky `tmp_function_cache` and use `FunctionSpace.get_work_function` instead.
> Remove temp function cache

- scripts/visualize-output.py
- thetis/exporter.py
- thetis/solver.py
- thetis/solver2d.py
Updates related to new firedrake VTK output.
> New VTK outputs

- test/swe2d/test_steady_state_basin_mms.py
- test/swe2d/test_steady_state_channel_mms.py
- thetis/options.py
- thetis/shallowwater_eq.py
- thetis/solver2d.py
- thetis/utility.py
This is a follow up from #10. Implements Interior Penalty viscosity scheme for the depth-integrated equations.
> Ip viscosity thetis

- examples/lockExchange/runTestSuite.py
- examples/lockExchange/submitRuns.py
- examples/overflow/overflow.py
- examples/rhineROFI/rhineROFI.py
- examples/rhineROFI/rhineROFI2d.py
- examples/tracerBox/tracerBox3d.py
- test/firedrake/test_divergence_2d.py
- test/firedrake/test_implicit_diffusion.py
- test/momentumEq/test_h-viscosity_mes.py
- test/momentumEq/test_v-viscosity_mes.py
- test/momentumEq/visu_viscosity.pvsm
- test/tracerEq/test_h-diffusion_mes.py
- test/tracerEq/test_v-diffusion_mes.py
- test/tracerEq/visu_diffusion.pvsm
- thetis/coupled_timeintegrator.py
- thetis/exporter.py
- thetis/momentum_eq.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/turbulence.py
- thetis/utility.py
Reimplemented 3D diffusion operators with interior penalty method. Added MES tests against analytical solution.
> Viscosity 3D

- test/momentumEq/test_h-viscosity_mes.py
- test/momentumEq/test_v-viscosity_mes.py
- test/tracerEq/test_h-diffusion_mes.py
- test/tracerEq/test_v-diffusion_mes.py
- thetis/__init__.py
- thetis/coupled_timeintegrator.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/utility.py
Just annotate the different bits of code with PETSc "Stages".
> Rework timings for new petsc logging

- test/swe2d/generate_basin_mms_setup.py
- test/swe2d/test_steady_state_basin_mms.py
- uses ufl expressions
- fixed invalid depth expression bug
- added a sympy script for computing residuals symbolically
> Reimplemented swe basin test

- thetis/shallowwater_eq.py
- thetis/solver2d.py
Channel2d example still fails to run successfully.
> Fix call to sspimex for swe

- examples/channel2d/channel2d.py
use extimated stable dt for explicit time integrators
> fix channel2d example

- test/callback/test_diagnostic_hdf5_output.py
- test/tracerEq/test_consistency.py
- thetis/__init__.py
- thetis/callback.py
- thetis/options.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/utility.py
New implementation of callback functions.
> Generic callbacks

- test/slopelimiter/test_slopelimiter.py
- test/tracerEq/test_consistency.py
- thetis/limiter.py
- thetis/solver.py
Now that some limiting functionality is in Firedrake itself, remove some
code in thetis.  Currently we just have to override the compute_bounds
function to also compute min/max at top and bottom.
This is in part to open a discussion...
> limiter: Subclass new Firedrake VertexBasedLimiter

- examples/lockExchange/diagnostics.py
- examples/lockExchange/lockExchange.py
- examples/lockExchange/plotting.py
- scripts/visualize-output.py
- test/callback/test_diagnostic_hdf5_output.py
- test/tracerEq/test_consistency.py
- thetis/callback.py
- thetis/solver.py
- thetis/solver2d.py
- tox.ini
So here's a draft what the callback api could look like.
Changes:
- solver object is now given to `DiagnosticCallback` constructor and stored in the class
- thus `__call__` and `evaluate` do not take any arguments
- renamed `__str__` as `message_str`
> Callback update

- .drone.yml
- tox.ini
Adds a configuration file for drone (hooked up with http://jenkins.ese.ic.ac.uk:8000/thetisproject/thetis).  Let's see if it works!
> Drone CI configuration

- .drone.yml
for example, see here: https://codecov.io/gh/thetisproject/thetis/tree/1c87bd9a611f0d381b99ba0f02a2ad3ab88b838f
> drone: Enable code coverage reporting

- examples/channel2d/channel2d.py
- examples/tidalfarm/tidalfarm.py
- scripts/visualize-output.py
- test/swe2d/test_standing_wave.py
- test/swe2d/test_steady_state_channel.py
- test/swe2d/test_steady_state_channel_mms.py
- test_adjoint/test_swe_adjoint.py
- thetis/callback.py
- thetis/coupled_timeintegrator.py
- thetis/equation.py
- thetis/exporter.py
- thetis/field_defs.py
- thetis/implicitexplicit.py
- thetis/limiter.py
- thetis/momentum_eq.py
- thetis/options.py
- thetis/physical_constants.py
- thetis/rungekutta.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/stability_functions.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/turbulence.py
- thetis/utility.py
Adding docstrings to all classes/functions. Adding math to all equation docstrings.
Addresses some points of #76
> Add documentation

- test/firedrake/test_implicit_friction.py
- test/momentumEq/test_v-viscosity_mes.py
- test/tracerEq/test_v-diffusion_mes.py
- thetis/momentum_eq.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/utility.py
FIAT elements are now finat elements.  Fixes #87.
> Update to firedrake changes

- test/swe2d/test_atmospheric_pressure.py
- thetis/options.py
- thetis/shallowwater_eq.py
- thetis/solver2d.py
Atmospheric pressure term is useful for storm surge modelling
> Add atmospheric pressure forcing term

- docs/source/model_formulation_2d.rst
- examples/balzano/balzano.py
- test/swe2d/test_thacker.py
- thetis/options.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
Wetting-drying scheme as in Karna et al (2010).
The test case I've added uses the Thacker case and compares the elevation at the centre of the domain after one oscillation period, and does this for two (relatively coarse) meshes.
If something more sophisticated than this is required, I can revisit.
> Wetting and drying

- docs/source/animationgrid.rst
Adding two videos where Thetis is used to simulate the operation of tidal lagoons & barrages
> Add two videos to website frontpage.

- thetis/limiter.py
- thetis/utility.py
Remove obsolete `FunctionSpace.bt_masks` API. Replaced by `get_facet_mask` method.
> Fixes for variable layers

- requirements.txt
- test/interpolation/test_gridinterpolator.py
- test/interpolation/test_lintimeinterp.py
- test/interpolation/test_netcdftimeinterp.py
- test/interpolation/test_vect_rotation.py
- thetis/__init__.py
- thetis/coordsys.py
- thetis/interpolation.py
- thetis/timezone.py
Added generic routines for interpolating external data on Firedrake fields.
In general, we want to read time series from a file tree, where it may be necessary to interpolate the data in space onto the local Firedrake grid. Then we need to be able to locate previous/next defined time steps in the file tree, and then do linear interpolation in between. To this end the problem is divided into multiple parts:
- Generic `GridInterpolator` that can interpolate data between grids using Delaunay triangulation
- `SpatialInterpolator` that builds a `GridInterpolator` for the local mesh
- `FileTreeReader` that returns data for a certain time step in a file (applying necessary spatial interp.)
- `TimeParser` that parses all the time steps that are stored in a file
- `TimeSearch` object that scans a …
> Interpolation routines for external forcings

- examples/baroclinic_eddies/baroclinic_eddies.py
- examples/dome/dome.py
- examples/lockExchange/lockExchange.py
- test/continuity3d/test_continuity_mes.py
- test/firedrake/test_divergence_2d.py
- test/momentumEq/test_h-viscosity_mes.py
- test/momentumEq/test_v-viscosity_mes.py
- test/tracerEq/test_h-advection_mes.py
- test/tracerEq/test_h-diffusion_mes.py
- test/tracerEq/test_steady_adv-diff_mms.py
- test/tracerEq/test_v-diffusion_mes.py
- thetis/callback.py
- thetis/coupled_timeintegrator.py
- thetis/limiter.py
- thetis/momentum_eq.py
- thetis/options.py
- thetis/rungekutta.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/utility.py
Updates and fixes for the 3D solver that are needed for baroclinic eddies test and Columbia River plume application.
> 3D solver updates

- thetis/callback.py
- thetis/coupled_timeintegrator.py
- thetis/equation.py
- thetis/utility.py
Minor changes for fixing parallel iteration order
> More fixes for parallel safe iteration

- examples/baroclinic_channel/baroclinic_channel.py
- examples/baroclinic_channel/visu.pvsm
- examples/baroclinic_eddies/baroclinic_eddies.py
Updates for baroclinic eddies test.
Also added new eddying channel test by Danilov (2012).
> Baroclinic eddies test

- test/solver3d/generate_source_terms.py
- test/solver3d/test_baroclinic_mms.py
- test/solver3d/test_barotropic_mes.py
Adds 3d solver convergence tests used in the 3D DG discretization paper. If run from the command line these tests reproduce the plots from the paper.
> 3D solver convergence tests

- test/bottomFriction/test_bottom_friction.py
- test/conftest.py
- test/swe2d/test_steady_state_basin_mms.py
- test/tracerEq/test_consistency.py
- test/tracerEq/test_h-diffusion_mes.py
- test/turbulence/test_katophillips.py
- test_adjoint/conftest.py
Remove Travis test setup that's now obsolete.
> Remove Travis test setup

- test/tracerEq/test_consistency.py
Minor correction and testing pull requests
> Correcting non_lin to use_nonlinear_equations

- docs/source/model_formulation_3d.rst
Remove obsolete time integrators from documetation
> Remove obsolete time integrators from documetation

- examples/tidal_barrage/modules/input_barrages.py
- examples/tidal_barrage/modules/tools.py
Updated callback for the tidal barrage example
> Lagoon callback fix

- examples/baroclinic_eddies/baroclinic_eddies.py
- examples/baroclinic_eddies/submitRuns.py
- examples/lockExchange/lockExchange.py
- examples/lockExchange/submitRuns.py
- thetis/limiter.py
- thetis/options.py
- thetis/utility.py
Updates for 3D model test cases
- adds support for quad meshes
- change `options.use_lax_friedrichs_tracer` to `False` by default
- updates for lock exchange and baroclinic eddies test
> Update 3D tests

- examples/channel3d/channel3d.py
- examples/columbia_plume/atm_forcing.py
- examples/dome/diagnostics.py
- examples/freshwaterCylinder/freshwaterCylinder.py
- examples/idealizedEstuary/warnerEstuary.py
- examples/lockExchange/lockExchange.py
- examples/lockExchange/plotting.py
- examples/tidal_barrage/lagoon2d.py
- examples/tidal_barrage/modules/input_barrages.py
- examples/tidal_barrage/modules/lagoon_operation.py
- thetis/assembledschur.py
- thetis/configuration.py
- thetis/momentum_eq.py
- thetis/rungekutta.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/stability_functions.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/tracer_eq_2d.py
- thetis/turbulence.py
- thetis/utility.py
mostly:
- W605 invalid escape sequence
- W504 line break after binary operator
> fixes for more strict flake8 style checking

- docs/source/publications.rst
- thetis/configuration.py
- fix traitlets
- add GMD paper on website
- add citing instructions on website
> Add GMD paper on website

- requirements.txt
Otherwise I can't run the demos with a clean install.
> Add pytz to requirements.txt

- docs/source/animationgrid.rst
- docs/source/index.rst
Fix embedded animations in webpage: all URLs should be https
> docs: embed animations in https

- docs/source/_themes/thetis/layout.html
- docs/source/index.rst
- test/momentumEq/test_h-viscosity_mes.py
- test/slopelimiter/test_slopelimiter.py
- thetis/options.py
Tim rebuilt the jenkins frontend which resulted in everything moving around.
> docs: Fix links to Jenkins

- thetis/utility.py
In preparation for the upcoming firedrake update.
> remove obsolete C expressions

- examples/tidalfarm/tidalfarm.py
- test/firedrake/test_implicit_friction.py
- test/swe2d/test_atmospheric_pressure.py
- test/swe2d/test_steady_state_basin_mms.py
- test/swe2d/test_steady_state_channel.py
- test/swe2d/test_steady_state_channel_mms.py
- test/swe2d/test_thacker.py
- test_adjoint/test_swe_adjoint.py
- thetis/options.py
- thetis/rungekutta.py
- thetis/timeintegrator.py
This is to fix the warnings associated with the {'option': True} => {'option': None} transition.
> Fix boolean petsc options warnings

- test/swe2d/test_thacker.py
- thetis/shallowwater_eq.py
Minor fixes to Riemann fluxes in the 2D shallow water equations. Improves errors near curved land boundaries.
> Fix 2d model Riemann fluxes

- examples/bottomFriction/plot_results.py
- examples/bottomFriction/steadyChannel.py
- examples/columbia_plume/cre-plume.py
- examples/columbia_plume/test_bathy_smoothing.py
- examples/dome/dome.py
- examples/idealizedEstuary/warnerEstuary.py
- examples/katophillips/katophillips.py
- examples/katophillips/plot_results.py
- scripts/visualize-output.py
- thetis/coupled_timeintegrator.py
- thetis/options.py
- thetis/solver.py
- thetis/stability_functions.py
- thetis/turbulence.py
Turbulence model updates:
- Vertical integration uses 2nd order DIRK22 scheme
- Fix stability functions
- Fix turbulence initialization
- Update turbulence parameters
- Update examples
> Turbulence model updates

- thetis/limiter.py
- thetis/timeintegrator.py
Removes all obsolete `force_evaluation` calls.
> Remove all calls to force_evaluation

- test/tracerEq/test_h-advection_mes_2d.py
- thetis/coupled_timeintegrator_2d.py
- thetis/options.py
- thetis/tracer_eq_2d.py
As part of my conservative tracer 2d I have created this separate pull request where I have changed the implementation of the corrective velocity factor (see previous pull request https://github.com/thetisproject/thetis/pull/164). This is because I realised that the correction factor also needed to be applied to the boundary conditions which made a difference in the case of the conservative tracer.
> Corrective vel factor

- Makefile
- test/conftest.py
- test/firedrake/test_implicit_diffusion.py
- test/firedrake/test_implicit_friction.py
- test/momentumEq/test_h-viscosity_mes.py
- test/momentumEq/test_v-viscosity_mes.py
- test/operations/test_hcc_metric.py
- test/operations/test_operations_2d-3d.py
- test/solver3d/generate_source_terms.py
- test/swe2d/generate_basin_mms_setup.py
- test/swe2d/test_anisotropic.py
- test/swe2d/test_standing_wave.py
- test/time_integration/test_convergence_ode.py
- test/tracerEq/test_bcs_2d.py
- test/tracerEq/test_consistency_2d.py
- test/tracerEq/test_h-advection_mes.py
- test/tracerEq/test_h-advection_mes_2d.py
- test/tracerEq/test_h-diffusion_mes.py
- test/tracerEq/test_h-diffusion_mes_2d.py
- test/tracerEq/test_steady_adv-diff_mms_2d.py
- test/tracerEq/test_v-diffusion_mes.py
Due to a typo in the Makefile the test suite was not tested for PEP8 errors. Fixes Makefile and all PEP8 errors.
> PEP8 test suite

- test/firedrake/test_divergence_2d.py
- test/firedrake/test_implicit_friction.py
- test/time_integration/test_convergence_ode.py
- test/tracerEq/test_bcs_2d.py
Fixes time integration test: assigning a Constant to a mixed function space is no longer allowed.
> Fix tests for firedrake gem update

- test/firedrake/test_implicit_friction.py
- thetis/solver.py
- thetis/solver2d.py
Suggesting this minor fix due to python3.8 updates (time.clock() is not working anymore)
> update clock to perf_counter

- thetis/exporter.py
Currently the coordinate caching only works for DG function space. This PR removes the cache altogether fixing the issue #208 with CG outputs.
Removing the cache imposes a performance hit as a new coordinate field will be allocated in each `File` object. This issue will be dealt with in Firedrake instead (see firedrakeproject/firedrake/pull/1744).
> Remove coordinate function caching from outputs

- docs/source/conf.py
- docs/source/publications.rst
> Update website publication list

- docs/source/publications.rst
Add one more missing publication.
> Add more publications to website

- examples/point_discharge/point_discharge.py
- test/tracerEq/test_point_discharge.py
- thetis/options.py
- thetis/solver2d.py
Following the closing of issue #188, this PR acts to check that the 2D steady state tracer solver works.
Convergence of the error due to evaluating two linear functionals is assessed under uniform mesh refinement. Convergence rates for the case `hydrodynamics=False` below.
(Aligned source and receiver)
(Offset source and receiver)
This could be a test, if that would be useful / there aren't too many similar tests.
> Point discharge with diffusion example

- docs/source/animationgrid.rst
- docs/source/publications.rst
- Adds two publications for 2021
- Adds Columbia River plume animation on the front page
> Update publications on website

- docs/source/documentation.rst
- docs/source/model_formulation_2d.rst
- docs/source/sediment_formulation_2d.rst
- docs/source/tracer_formulation_2d.rst
- thetis/configuration.py
- thetis/conservative_tracer_eq_2d.py
- thetis/solver2d.py
* Fix doc build
* Add DIRK22 to available time integrators
* Add a note on wetting and drying parameters
* Add a page on the 2D tracer model
* Add a page on the 2D sediment model
@mc4117: am I right in saying that the Exner equation should be solved in P1 space? It looks to me like it is solved in whatever function space the user defines the bathymetry in, but maybe I misread.
> Update 2D model manual pages

- Jenkinsfile
- demos/demo_2d_tracer.py
- demos/demo_references.bib
- docs/Makefile
- docs/source/conf.py
- docs/source/documentation.rst
- thetis/solver2d.py
I created this demo by translating the Firedrake [DG advection](https://firedrakeproject.org/demos/DG_advection.py.html) demo into Thetis.
There were a few tweaks required to import the bibliography and also I made sure `'DQ'` is specified on quads, to avoid getting lots of `UFL:WARNING Discontinuous Lagrange element requested on quadrilateral, creating DQ element.` warnings.
> 2D tracer demo

- examples/baroclinic_eddies/diagnostics.py
- examples/bottomFriction/ekman_bottom.py
- examples/bottomFriction/plot_results.py
- examples/bottomFriction/steadyChannel.py
- examples/lockExchange/diagnostics.py
- examples/nonhydrostatic_cases/solitary_wave_nh/solitary_wave_2d.py
- test/bottomFriction/test_bottom_friction.py
- test/bottomFriction/test_ekman_bottom.py
- test/solver3d/test_baroclinic_mms.py
- test/solver3d/test_barotropic_mes.py
- test/swe2d/test_standing_wave.py
- test/swe2d/test_standing_wave_nh.py
- test/swe2d/test_steady_state_channel.py
- test/swe2d/test_steady_state_channel_mms.py
- thetis/configuration.py
- thetis/coupled_timeintegrator.py
- thetis/momentum_eq.py
- thetis/solver.py
- thetis/utility3d.py
Updated 3D bottom friction formulation. Revised formulation ensures that friction cannot cause velocity sign change in the bottom element. Uses a parametrization for the drag coefficient.
> Consistent 3d bottom friction

- examples/dome/dome.py
- test/continuity3d/test_continuity_mes.py
- test/momentumEq/test_h-viscosity_mes.py
- test/momentumEq/test_v-viscosity_mes.py
- test/tracerEq/test_steady_adv-diff_mms.py
- thetis/solver.py
- thetis/solver2d.py
Also includes a couple of bugfixes in the 2D model.
> Implement add_new_field to 3d solver

- demos/demo_2d_multiple_tracers.py
- test/time_integration/test_convergence_ode.py
- thetis/coupled_timeintegrator.py
- thetis/coupled_timeintegrator_2d.py
- thetis/field_defs.py
- thetis/implicitexplicit.py
- thetis/options.py
- thetis/rungekutta.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/timeintegrator.py
Also add some checks to `add_new_tracer`, as discussed in last Thetis meeting.
> Pass TimeStepperOptions to timesteppers

- demos/demo_2d_multiple_tracers.py
- demos/demo_2d_tracer.py
- docs/Makefile
- docs/source/documentation.rst
- docs/source/gen_model_options_doc.py
- docs/source/model_formulation_2d.rst
- docs/source/sediment_formulation_2d.rst
- docs/source/tracer_formulation_2d.rst
- examples/sediment_meander_2d/meander_hydro.py
- examples/sediment_trench_2d/trench_example.py
- examples/sediment_trench_2d/trench_hydro.py
- test/sediment/test_migrating_trench.py
- test/tracerEq/test_bcs_2d.py
- test/tracerEq/test_consistency_2d.py
- test/tracerEq/test_h-advection_mes_2d.py
- test/tracerEq/test_h-diffusion_mes_2d.py
- test/tracerEq/test_point_discharge.py
- test/tracerEq/test_steady_adv-diff_mms_2d.py
- thetis/coupled_timeintegrator_2d.py
- thetis/options.py
- thetis/solver2d.py
Addresses most of the points in #253, as well as updating the tracer and sediment model docs.
If these changes look okay then I will summarise the API changes in this PR and #251, put them in a page on the wiki and then publicise on Slack, etc.
> Deprecate solve tracer

- test/tracerEq/test_point_discharge.py
fixes `tracerEq/test_point_discharge.py`
> Do not save outputs in tests

- demos/01-2d-channel.ipynb
- demos/02-2d-tsunami.ipynb
- test/examples/test_notebooks.py
Recent experience with Firedrake notebooks bit rotting suggests it is a good idea to test them.
> Test notebooks

- thetis/callback.py
- thetis/coupled_timeintegrator.py
- thetis/coupled_timeintegrator_2d.py
- thetis/equation.py
- thetis/exporter.py
- thetis/implicitexplicit.py
- thetis/interpolation.py
- thetis/limiter.py
- thetis/rungekutta.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/timeintegrator.py
- thetis/turbines.py
- thetis/turbulence.py
- thetis/utility.py
- thetis/utility3d.py
I applied PETSc event logging throughout Thetis and found it really useful for profiling Thetis-based codes.
One thing I noticed was that a decent chunk (of an admittedly small application) was spent computing horizontal element sizes and facet areas. This is because they were using the default solver parameters (full LU as preconditioner). To avoid this, I've used Firedrake's `MassInvPC` for the former and an application of Jacobi for the latter.
> Event logging

- test/conftest.py
- test/solver3d/test_baroclinic_mms.py
- test/solver3d/test_barotropic_mes.py
- test/swe2d/test_steady_state_channel.py
- thetis/solver.py
- thetis/utility.py
A bug was introduced in #276 and reported by @jhill1. Fix suggested by @wence-.
> Fix error using ILU in parallel

- thetis/__init__.py
- thetis/callback.py
- thetis/conservative_tracer_eq_2d.py
- thetis/coupled_timeintegrator.py
- thetis/coupled_timeintegrator_2d.py
- thetis/equation.py
- thetis/exner_eq.py
- thetis/exporter.py
- thetis/implicitexplicit.py
- thetis/limiter.py
- thetis/momentum_eq.py
- thetis/physical_constants.py
- thetis/rungekutta.py
- thetis/sediment_eq_2d.py
- thetis/shallowwater_eq.py
- thetis/solver.py
- thetis/solver2d.py
- thetis/stability_functions.py
- thetis/timeintegrator.py
- thetis/tracer_eq.py
- thetis/tracer_eq_2d.py
- thetis/turbulence.py
- thetis/utility.py
- thetis/utility3d.py
I don't think we need these any more.
> Remove future imports

- thetis/solver.py
- thetis/solver2d.py
- thetis/utility.py
Thought it would be a neat way to do this.
> Decorator for unfreezing objects

- test/interpolation/test_netcdftimeinterp.py
- thetis/callback.py
- thetis/forcing.py
- thetis/interpolation.py
- ATMInterpolator and TidalBoundary work on the sphere
- TimeSeriesCallback works on the sphere with 3D coordinate vectors
- Adds Large and Yeager (2009) wind stress formulation
> Extend 2D forcing routines to work on the sphere

- docs/source/publications.rst
- thetis/forcing.py
@mc4117 may want to check she is happy with the citation of her paper.
> Add two recent papers

- examples/freshwaterCylinder/freshwaterCylinder.py
- test/swe2d/test_anisotropic.py
- test/swe2d/test_rossby_wave.py
- thetis/configuration.py
- thetis/diagnostics.py
Introduce a diagnostic for computing dynamic pressure in 2D or 3D.
Also add some input checking for ``VorticityCalculator2D`` and ``HessianRecoverer2D``.
> KineticEnergyCalculator

- examples/channel_inversion/forward_run.py
- examples/channel_inversion/inverse_problem.py
- examples/channel_inversion/model_config.py
- examples/channel_inversion/plot_elevation_progress.py
- examples/channel_inversion/visu.pvsm
- test/examples/test_examples.py
- test_adjoint/examples/test_examples.py
- thetis/inversion_tools.py
- thetis/utility.py
Simple 2D channel test case to demonstrate Thetis adjoint capabilities. Forward run is used to store elevation time series at some locations. Inverse model can then be used to find the original model fields, i.e. bathymetry, bottom friction coefficient, and initial elevation field.
> Simple channel inversion modeling example

- thetis/forcing.py
- thetis/interpolation.py
- thetis/solver2d.py
Small fixes for 2D Baltic Sea simulation.
> Updates for 2D Baltic Sea application

- thetis/forcing.py
This is needed to support different TPXO versions. File names were hard-coded to TPXO 9v1 file names, now set to 9v5a by
default.
> TPXOTidalBoundaryForcing supports custom netcdf file names

- examples/tohoku_inversion/forward_run.py
- examples/tohoku_inversion/inverse_problem.py
- examples/tohoku_inversion/model_config.py
It is common practice to subtract the initial elevation field from the bathymetry field in tsunami simulations.
> Tohoku: subtract initial elevation from bathymetry

- thetis/solver.py
- thetis/solver2d.py
It would be nice to be able to continue writing to the same log file when a new solver is created, e.g. during mesh adaptive runs.
> Option for appending to log

- examples/columbia_plume/atm_forcing.py
- examples/north_sea/model_config.py
- test/interpolation/test_vect_rotation.py
- thetis/configuration.py
- thetis/coordsys.py
- thetis/coupled_timeintegrator.py
- thetis/coupled_timeintegrator_2d.py
- thetis/diagnostics.py
- thetis/forcing.py
- thetis/implicitexplicit.py
- thetis/interpolation.py
- thetis/limiter.py
- thetis/rungekutta.py
- thetis/timeintegrator.py
- thetis/turbulence.py
- thetis/utility.py
- thetis/utility3d.py
Adds coordinate system object that provides transformations to/from latitude, longitude coordinate system.
API symmary:
```python
coordsys = UTMCoordinateSystem(utm_zone=34)
lon, lat = ...  # numpy arrays
x, y = coordsys.to_xy(lon, lat)  # mesh coordinates
lon, lat = coordsys.to_lonlat(x, y)  # inverse
u_east, v_north = ...  # vector components at (lon, lat) locations
vect_rotator = coordsys.get_vector_rotator(lon, lat)
u_x, v_y = vect_rotator(u_east, v_north)
mesh2d = ...
ll = get_mesh_lonlat_function(mesh2d)
```
The (lon, lat) coordinate system is WGS84.
> Coordinate system object

- test/swe2d/test_atmospheric_pressure.py
- test/swe2d/test_standing_wave.py
- test/swe2d/test_standing_wave_nh.py
- test/swe2d/test_steady_state_channel.py
- test/swe2d/test_steady_state_channel_mms.py
- test/swe2d/test_thacker.py
> Fix PEP8 errors

- examples/tohoku_inversion/sources.py
- thetis/configuration.py
- thetis/options.py
Apparently "from traitlets import *" doesn't actually import anything we wan't. Import symbols explicitly instead.
> Fix thetis with traitlets 5.8

- test/sphere/test_williamson.py
> Min, Max -> min_value, max_value

- test/sphere/test_williamson.py
- thetis/exner_eq.py
- thetis/utility.py
These were changes to form2indicator
related to the Cofunction introduction that have been fixed in goalie (formerly part of pyroteus).
> Incorporate changes to form2indicator from goalie.

- examples/tohoku_inversion/sources.py
- thetis/exporter.py
- thetis/interpolation.py
- thetis/limiter.py
- thetis/utility.py
- thetis/utility3d.py
Fixed few API changes in latest firedrake and UFL.
> move to new ufl api

- docs/source/publications.rst
We should also rebuild the website after merging this (I notice Jon's additions in #348 don't appear).
> Add two 2023 papers

- docs/source/publications.rst
> Remove Zhang '23

- docs/source/docutils.conf
This is based on https://stackoverflow.com/questions/76574318/
> Fix scaling of team fotos with newer sphinx/docutils

- thetis/coordsys.py
Adds south= kwarg, default to False (Northern Hemisphere)
> Enable southern hemipshere in UTMCoordinateSystem

- thetis/utility.py
Update tsfc imports - see Firedrake [#3929](https://github.com/firedrakeproject/firedrake/pull/3929)
> Update tsfc imports (Firedrake #3929)
